"""Tests for billing/superbill endpoints."""
import json
import pytest
from conftest import clinician_headers, client_headers


async def _register_clinician(client):
    await client.post(
        "/api/auth/register",
        json={"role": "clinician"},
        headers=clinician_headers(),
    )


async def _create_signed_note(client):
    """Create a client, encounter, and signed note for superbill generation."""
    # Create client via intake
    intake_resp = await client.post(
        "/api/intake",
        json={
            "demographics": {"name": "Billing Client", "dateOfBirth": "1990-01-01"},
            "presentingConcerns": "Billing test",
        },
        headers=client_headers(),
    )
    encounter_id = intake_resp.json()["encounterId"]

    # Generate note
    gen_resp = await client.post(
        "/api/notes/generate",
        json={"encounter_id": encounter_id},
        headers=clinician_headers(),
    )
    note_id = gen_resp.json()["note_id"]

    # Sign note (this auto-generates superbill)
    await client.post(
        f"/api/notes/{note_id}/sign",
        json={"signature_data": "data:image/png;base64,fakeSig"},
        headers=clinician_headers(),
    )

    return note_id


async def test_generate_superbill(client):
    """POST /api/superbills/generate creates a superbill for a signed note."""
    await _register_clinician(client)
    note_id = await _create_signed_note(client)

    # The superbill may already have been auto-generated by the sign endpoint
    resp = await client.post(
        "/api/superbills/generate",
        json={"note_id": note_id},
        headers=clinician_headers(),
    )
    # Should be 200 (returns existing or creates new)
    assert resp.status_code == 200
    data = resp.json()
    assert "id" in data
    assert "cpt_code" in data


async def test_list_superbills(client):
    """GET /api/superbills returns all superbills with summary."""
    await _register_clinician(client)
    resp = await client.get("/api/superbills", headers=clinician_headers())
    assert resp.status_code == 200
    data = resp.json()
    assert "superbills" in data
    assert "summary" in data
    assert "total_billed" in data["summary"]


async def test_list_superbills_with_filter(client):
    """GET /api/superbills?status=generated filters by status."""
    await _register_clinician(client)
    resp = await client.get(
        "/api/superbills", params={"status": "generated"},
        headers=clinician_headers(),
    )
    assert resp.status_code == 200


async def test_update_superbill_status(client):
    """PATCH /api/superbills/{id}/status updates billing status."""
    await _register_clinician(client)
    note_id = await _create_signed_note(client)

    # Generate
    gen_resp = await client.post(
        "/api/superbills/generate",
        json={"note_id": note_id},
        headers=clinician_headers(),
    )
    sb_id = gen_resp.json()["id"]

    # Update status
    resp = await client.patch(
        f"/api/superbills/{sb_id}/status",
        json={"status": "submitted"},
        headers=clinician_headers(),
    )
    assert resp.status_code == 200
    assert resp.json()["new_status"] == "submitted"


async def test_update_superbill_invalid_status(client):
    """PATCH /api/superbills/{id}/status rejects invalid status."""
    await _register_clinician(client)
    note_id = await _create_signed_note(client)

    gen_resp = await client.post(
        "/api/superbills/generate",
        json={"note_id": note_id},
        headers=clinician_headers(),
    )
    sb_id = gen_resp.json()["id"]

    resp = await client.patch(
        f"/api/superbills/{sb_id}/status",
        json={"status": "invalid_status"},
        headers=clinician_headers(),
    )
    assert resp.status_code == 400


async def test_my_superbills(client):
    """GET /api/superbills/my returns client's own superbills."""
    await client.post(
        "/api/auth/register",
        json={"role": "client"},
        headers=client_headers(),
    )
    resp = await client.get("/api/superbills/my", headers=client_headers())
    assert resp.status_code == 200
    data = resp.json()
    assert "superbills" in data
    assert "client_balance" in data
